# Generated by Django 4.0 on 2021-12-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('CHROM', models.CharField(max_length=250)),
                ('POS', models.IntegerField()),
                ('ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('REF', models.CharField(max_length=250)),
                ('ALT_1', models.CharField(blank=True, max_length=250)),
                ('ALT_2', models.CharField(blank=True, max_length=250)),
                ('ALT_3', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
