# Generated by Django 4.0 on 2021-12-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcf_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
